version: "3.3"

services:
  web:
    build: .
    ports:
      - 80:80
    tty: true
    volumes:
      - source: '\\.\pipe\docker_engine'
        target: '\\.\pipe\docker_engine'
        type: npipe
networks:
  default:
    external:
     name: "nat"