version: "3.3"

services:
 web:
  build: ./web
  ports:
   - "80:80"
   - "64079:64079"
  depends_on:
   - db
  tty:
    true
 db:
  build: ./db
  expose:
   - "1433"
  tty:
    true

networks:
 default:
  external:
   name: "test"
